
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 08:41:02 COT 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ORDENARDS = 4;
  public static final int DIGITO = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ORDENARAS = 3;
  public static final int FINLINEA = 2;
}

